create table if not exists journal.risk_plan_evidence (
    id integer generated by default as identity primary key,
    trade_group text not null,
    image_path text not null,
    provider text not null,
    model text not null,
    extraction_json text not null,
    applied_json text,
    status text not null default 'pending'
        check (status in ('pending','applied','rejected')),
    created_at timestamptz not null default now(),
    applied_at timestamptz
);

create index if not exists idx_risk_plan_group
    on journal.risk_plan_evidence(trade_group);

alter table journal.risk_plan_evidence enable row level security;

revoke all privileges on journal.risk_plan_evidence from anon, authenticated;
revoke all privileges on sequence journal.risk_plan_evidence_id_seq from anon, authenticated;

insert into journal.schema_migrations (migration_id)
values ('20260926_002_risk_plan_evidence')
on conflict (migration_id) do nothing;
