create table journal.smoking_gun_reports (
    id integer generated by default as identity primary key,
    account_id integer not null references journal.accounts(id) on delete cascade,
    title text not null,
    date_from text not null,
    date_to text not null,
    generated_at timestamptz not null default now(),
    report_version text not null,
    analytics_engine_version text not null,
    behavior_version text not null,
    analysis_provider text,
    analysis_model text,
    trade_count integer not null,
    gross_pnl double precision,
    net_pnl double precision,
    primary_edge text,
    primary_leak text,
    data_fingerprint text not null,
    filters_json jsonb not null default '{}'::jsonb,
    source_metrics_json jsonb not null,
    diagnosis_json jsonb,
    action_plan_json jsonb,
    export_manifest_json jsonb not null default '{}'::jsonb,
    status text not null default 'complete'
        check (status in ('complete','draft','failed')),
    unique (account_id, date_from, date_to, data_fingerprint, report_version)
);

create index idx_smoking_gun_reports_account_generated
    on journal.smoking_gun_reports(account_id, generated_at desc);

create index idx_smoking_gun_reports_fingerprint
    on journal.smoking_gun_reports(data_fingerprint);

alter table journal.smoking_gun_reports enable row level security;

revoke all on table journal.smoking_gun_reports from public, anon, authenticated;
revoke all on sequence journal.smoking_gun_reports_id_seq from public, anon, authenticated;

insert into journal.schema_migrations (migration_id)
values ('20260926_002_smoking_gun_reports');
