create schema if not exists journal;

revoke all on schema journal from public;
revoke all on schema journal from anon;
revoke all on schema journal from authenticated;

create table journal.schema_migrations (
    migration_id text primary key,
    applied_at timestamptz not null default now()
);

create table journal.accounts (
    id integer generated by default as identity primary key,
    name text not null,
    type text not null check (type in ('day_trading','swing_trading','investment')),
    color text not null default '#6366f1',
    broker text,
    created_at timestamptz not null default now()
);

create table journal.trades (
    id integer generated by default as identity primary key,
    account_id integer not null references journal.accounts(id),
    trade_group text not null,
    date text not null,
    ticker text not null,
    instrument_type text not null check (instrument_type in ('STOCK','OPTION','FUTURE')),
    side text not null check (side in ('LONG','SHORT')),
    gross_pnl double precision,
    net_pnl double precision,
    commissions double precision default 0,
    executions text not null default '[]',
    option_expiry text,
    option_strike double precision,
    option_type text check (option_type in ('CALL','PUT') or option_type is null),
    source text not null default 'imported',
    imported_at timestamptz not null default now(),
    setup text,
    setup_grade text,
    setup_notes text,
    setup_features text,
    setup_source text default 'auto',
    mfe_pct double precision,
    mae_pct double precision,
    exit_efficiency double precision,
    unique (trade_group, account_id)
);

create table journal.diary_entries (
    id integer generated by default as identity primary key,
    account_id integer not null references journal.accounts(id),
    entry_date text not null,
    image_path text,
    raw_text text,
    ai_analysis text,
    created_at timestamptz not null default now()
);

create table journal.trade_analysis (
    id integer generated by default as identity primary key,
    trade_group text not null unique,
    ticker text not null,
    date text not null,
    strategy text,
    stop_loss double precision,
    risk_per_trade double precision,
    risk_reward double precision,
    r_multiple double precision,
    entry_reason text,
    exit_reason text,
    mistakes text,
    emotional_state text,
    notes text,
    ai_feedback text,
    match_confidence text check (
        match_confidence in ('high','medium','low','ambiguous','unmatched','manual')
        or match_confidence is null
    ),
    match_notes text,
    diary_entry_id integer references journal.diary_entries(id),
    target_price double precision,
    trade_rating integer,
    idea_source text
);

create table journal.trade_tags (
    id integer generated by default as identity primary key,
    trade_group text not null,
    tag_type text not null,
    tag_value text not null,
    source text not null check (source in ('ai','manual'))
);

create table journal.daily_summaries (
    id integer generated by default as identity primary key,
    account_id integer references journal.accounts(id),
    summary_date text not null,
    ai_content text not null,
    generated_at timestamptz not null default now(),
    unique (summary_date, account_id)
);

create table journal.settings (
    id integer generated by default as identity primary key,
    account_id integer not null default 0,
    key text not null,
    value text not null,
    unique (account_id, key)
);

create table journal.custom_setups (
    id integer generated by default as identity primary key,
    name text not null unique,
    side text,
    notes text,
    active integer not null default 1,
    created_at timestamptz not null default now()
);

create table journal.library_items (
    id integer generated by default as identity primary key,
    kind text not null check (kind in ('strategy','source','tag')),
    tag_type text not null default '',
    name text not null,
    description text,
    created_at timestamptz not null default now(),
    unique (kind, tag_type, name)
);

create table journal.library_aliases (
    id integer generated by default as identity primary key,
    kind text not null,
    tag_type text not null default '',
    alias text not null,
    canonical text not null,
    created_at timestamptz not null default now(),
    unique (kind, tag_type, alias)
);

create index idx_trades_account_date on journal.trades(account_id, date);
create index idx_trades_group on journal.trades(trade_group);
create index idx_analysis_group on journal.trade_analysis(trade_group);
create index idx_tags_group on journal.trade_tags(trade_group);

insert into journal.schema_migrations (migration_id)
values ('20260926_001_supabase_postgres');

alter table journal.schema_migrations enable row level security;
alter table journal.accounts enable row level security;
alter table journal.trades enable row level security;
alter table journal.diary_entries enable row level security;
alter table journal.trade_analysis enable row level security;
alter table journal.trade_tags enable row level security;
alter table journal.daily_summaries enable row level security;
alter table journal.settings enable row level security;
alter table journal.custom_setups enable row level security;
alter table journal.library_items enable row level security;
alter table journal.library_aliases enable row level security;

revoke all privileges on all tables in schema journal from anon, authenticated;
revoke all privileges on all sequences in schema journal from anon, authenticated;
revoke all privileges on all functions in schema journal from anon, authenticated;
alter default privileges in schema journal revoke all on tables from anon, authenticated;
alter default privileges in schema journal revoke all on sequences from anon, authenticated;
alter default privileges in schema journal revoke all on functions from anon, authenticated;
